from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from io import BytesIO

RISK_COLORS = {
    "Low": colors.HexColor("#3FB950"),
    "Medium": colors.HexColor("#D4A72C"),
    "High": colors.HexColor("#E8590C"),
    "Critical": colors.HexColor("#E5484D"),
}

def generate_incident_pdf(incident: dict) -> BytesIO:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle('TitleStyle', parent=styles['Heading1'], fontSize=18, spaceAfter=4)
    label_style = ParagraphStyle('LabelStyle', parent=styles['Normal'], textColor=colors.grey, fontSize=9)
    body_style = ParagraphStyle('BodyStyle', parent=styles['Normal'], fontSize=11, leading=16, spaceAfter=10)
    action_style = ParagraphStyle('ActionStyle', parent=styles['Normal'], fontSize=11, leading=16,
                                   textColor=colors.HexColor("#1a1a1a"), spaceAfter=10)

    elements = []

    elements.append(Paragraph("AI Cyber Defense Assistant", label_style))
    elements.append(Paragraph("Incident Report", title_style))
    elements.append(Paragraph(f"Incident ID: #{incident['id']}  |  Generated: {incident['created_at']}", label_style))
    elements.append(Spacer(1, 0.6*cm))

    risk_color = RISK_COLORS.get(incident['risk'], colors.grey)
    risk_table = Table([[f"Attack type: {incident['attack_type'] or 'None'}", f"Risk: {incident['risk']}"]],
                        colWidths=[9*cm, 6*cm])
    risk_table.setStyle(TableStyle([
        ('BACKGROUND', (1, 0), (1, 0), risk_color),
        ('TEXTCOLOR', (1, 0), (1, 0), colors.white),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
    ]))
    elements.append(risk_table)
    elements.append(Spacer(1, 0.6*cm))

    # --- Phase 2: Recommended Action highlight box ---
    recommended_action = incident.get('recommended_action')
    if recommended_action:
        action_bg = colors.HexColor("#FFF3CD")
        action_table = Table([[f"⚡ Recommended Action: {recommended_action}"]],
                              colWidths=[15*cm])
        action_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), action_bg),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor("#856404")),
            ('FONTSIZE', (0, 0), (-1, -1), 11),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('LEFTPADDING', (0, 0), (-1, -1), 12),
            ('ROUNDEDCORNERS', [4, 4, 4, 4]),
        ]))
        elements.append(action_table)
        elements.append(Spacer(1, 0.6*cm))

    elements.append(Paragraph("Root Cause / Reason", styles['Heading3']))
    elements.append(Paragraph(incident['reason'], body_style))

    elements.append(Paragraph("Recommended Actions", styles['Heading3']))
    for rec in incident['recommendations']:
        elements.append(Paragraph(f"&bull;&nbsp;&nbsp;{rec}", body_style))

    elements.append(Spacer(1, 1*cm))
    elements.append(Paragraph("Generated by AI Cyber Defense Assistant", label_style))

    doc.build(elements)
    buffer.seek(0)
    return buffer


def generate_summary_pdf(summary_data: dict) -> BytesIO:
    """Phase 7: Weekly/range summary report."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle('TitleStyle', parent=styles['Heading1'], fontSize=18, spaceAfter=4)
    label_style = ParagraphStyle('LabelStyle', parent=styles['Normal'], textColor=colors.grey, fontSize=9)
    body_style = ParagraphStyle('BodyStyle', parent=styles['Normal'], fontSize=11, leading=16, spaceAfter=6)
    h2_style = ParagraphStyle('H2Style', parent=styles['Heading2'], fontSize=13, spaceAfter=6, spaceBefore=12)

    elements = []

    elements.append(Paragraph("AI Cyber Defense Assistant", label_style))
    elements.append(Paragraph("Incident Summary Report", title_style))
    elements.append(Paragraph(
        f"Period: {summary_data['from_date']} to {summary_data['to_date']}  |  Generated: {summary_data['generated_at']}",
        label_style
    ))
    elements.append(Spacer(1, 0.8*cm))

    # Totals table
    totals = summary_data['totals']
    totals_table = Table([
        ["Total Incidents", "Critical", "High", "Medium", "Low"],
        [
            str(totals['total']),
            str(totals['critical']),
            str(totals['high']),
            str(totals['medium']),
            str(totals['low']),
        ]
    ], colWidths=[3*cm]*5)
    totals_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1a2233")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('BACKGROUND', (1, 1), (1, 1), colors.HexColor("#E5484D")),
        ('BACKGROUND', (2, 1), (2, 1), colors.HexColor("#E8590C")),
        ('BACKGROUND', (3, 1), (3, 1), colors.HexColor("#D4A72C")),
        ('BACKGROUND', (4, 1), (4, 1), colors.HexColor("#3FB950")),
        ('TEXTCOLOR', (1, 1), (-1, 1), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#dddddd")),
    ]))
    elements.append(totals_table)
    elements.append(Spacer(1, 0.6*cm))

    # Attack type breakdown
    elements.append(Paragraph("Breakdown by Attack Type", h2_style))
    breakdown = summary_data.get('attack_breakdown', {})
    if breakdown:
        breakdown_rows = [["Attack Type", "Count"]]
        for atype, count in sorted(breakdown.items(), key=lambda x: x[1], reverse=True):
            breakdown_rows.append([atype or "Unknown", str(count)])
        bt_table = Table(breakdown_rows, colWidths=[10*cm, 5*cm])
        bt_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1a2233")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#dddddd")),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ]))
        elements.append(bt_table)

    elements.append(Spacer(1, 1*cm))
    elements.append(Paragraph("Generated by AI Cyber Defense Assistant", label_style))

    doc.build(elements)
    buffer.seek(0)
    return buffer